server:
  port: 8890
#spring:
#  ai:
#    openai:
#      base-url: ${OPENAI_API_URL}
#      api-key: ${OPENAI_API_KEY}
#      chat:
#        options:
#          model: gpt-3.5-turbo
#          temperature: 0.7
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_API_URL}
      audio:
        transcription:
          options:
            model: whisper-1